### ISSUE TITLE
Link Scatter button seems broken

### ISSUE THREAD

**Issue by Soleone** [zachalam/AccountPhoto#1]
On https://accountphoto.com the **Link Scatter** button doesnt seem to do anything. Is this intentionally not implemented yet (I didn't notice `scatter-js` being included in `package.json`), or maybe not compatible with latest Scatter Desktop or something? Or just some temporary issue I'm encountering here?

I am in Chrome on Windows 10 using latest Scatter Desktop 9.6.0.

Not sure if it matters but when loading the page I see the following the javascript console:

```
manifest.json:1 Failed to load resource: the server responded with a status of 404 ()
manifest.json:1 Manifest: Line: 1, column: 1, Unexpected token.
```

**Comment by zachalam** [comment]
Hi @Soleone - thanks for raising the issue. I spent some time trying to re-diagnose on my system with Scatter desktop (same version as you). Unfortunately am unable to get an error on MacOS. 

You may have checked the wrong package.json file. The one in the frontend has scatter imported: 
https://github.com/zachalam/AccountPhoto/blob/master/frontend/package.json

![image](https://user-images.githubusercontent.com/832764/48656998-d9c03a80-e9e0-11e8-858e-1d580185357a.png)

When you get a chance, can you please try again and let me know what happens?
